spring:
  datasource:
#    url: jdbc:postgresql://postgres:5432/account_service
#    username: account
#    password: account123
#    driver-class-name: org.postgresql.Driver

# <=== H2 DB ====>
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  application:
    name: account

  profiles:
    active: prod

  config:
#    import: configserver:http://configserver:8071
    import: optional:configserver:http://localhost:8071
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    shutdown:
      enabled: true

  info:
    env:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9000/eureka

#configuration info endpoint
info:
  app:
    name: Account Microservice
    description: Suytry Bank Account App
    version: 1.0.0  # get from pom


resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
    instances:
      customerDetailSupport:
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30000
        permittedNumberOfCallsInHalfOpenState: 2