version: "3.8"
services:
  configserver:
    image: suytry123/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - suytrybanknet
    environment:
      GIT_TOKEN: ${GIT_TOKEN}
  account:
    image: suytry123/account:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - suytrybanknet
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
networks:
  suytrybanknet: