spring:
  application:
    name: configserver

  profiles:
    #active: native
    active: git

  cloud:
    config:
      server:
        #native:
          #search-locations: classpath:/config
          #search-locations: file:///C://bankdata//config

        git:
          uri: https://github.com/suytry123/bank-config-server
          clone-on-start: true
          default-label: main

server:
  port: 8071